### ISSUE TITLE
Menu option in issue list disappears after Mantis bt update to 2.25.1

### ISSUE THREAD

**Issue by priocomdevops** [Tagirijus/MantisBTTagiWorkflow#1]
The menu "configure columns" menu option that usually appears alongside 'print reports' ,'csv export' etc in the view issues menu div disappeared as soon as I upgraded my mantis from 2.24.3 to 2.25.1. 

I have tried installing and uninstalling, changing plugin priority etc numerous times but no luck.
Please assist.
kind regards.

**Comment by Tagirijus** [comment]
Hey there, I just checked on my local environment and disabled my plugin. I do not have a _"configure columns"_ even without my plugin enabled. Could it be that this change was made in v2.25.0 (the version I am checking right now locally)?

Please try to disable my plugin and tell me, if it still occurs. Also it would be nice, if you could tell me where exactly the menu-point is missing (view bugs page, right?). Thank you! (=

**Comment by priocomdevops** [comment]
Thanks so much for your quick response.
My profuse apologies.
I confused your plugin with another one.
Your plugin works flawlessly.
Kind regards.

**Comment by Tagirijus** [comment]
Ah, I see, hehe. No problem. You're welcome. Good luck finding a solution to you initial problem!
